### PR TITLE
Windows fixes

### PR DESCRIPTION
**Pull request by melted**
There's some nonsense when trying to install it yet. But this as far as I got during lunch, the bootstrap works and the libraries build at least.

### CODE REVIEW

**Comment by edwinb** [comment]
Brilliant, thank you! Should I wait until the install is successfull, or are you happy for me to merge now and do the rest later?

**Comment by melted** [comment]
You can merge now, it's useful as is.

**Comment by edwinb** [comment]
Done, thanks! I have a Windows machine lying around, though I don't really know how to use it for anything other than playing old games :). I should see if I can get it running myself now.

**Comment by melted** [comment]
The trick is to get msys2 and work just like in unix :-) https://www.msys2.org

**Pull request merged**
